name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    name: Unit Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint:check
      - name: Format
        run: yarn fmt:check
      - name: Test
        run: yarn test
